FROM openjdk:17-bullseye

RUN mkdir /app

RUN apt update

RUN apt install -y \
    wget \
    python3-pip \
    ffmpeg \
    imagemagick \
    zlib1g-dev \
    libjpeg-dev

RUN pip3 install --upgrade pip

RUN pip3 install \
    Pillow

RUN wget https://github.com/jeremynoesen/BoneBot/releases/download/1.5.7/BoneBot.jar -O /app/BoneBot.jar

WORKDIR /data
ENTRYPOINT ["java", "-jar", "/app/BoneBot.jar"]